##       Task # 4:  Predicting House Prices using Boston Housing dataset

## Importing libraries and Basic data wranggling

In [1]:
import numpy as np
import pandas as pd
import sklearn.preprocessing 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [2]:
data=pd.read_csv('Boston.csv')

In [3]:
df=data.copy()

In [4]:
df.shape

(506, 14)

In [5]:
df.head()

,Crime Rate,Residential Proportion,non-retail business acres/Town,Charles River,NO2 concentration,Average Rooms/Dwelling.,Prior Built Units Proportion,Distance to Employment Centres,Radial Highways Distance,ValueProperty/tax rate,Teacher/town,blacks/town,Lower Status Percent,median home price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [6]:
df.describe(include="all")

,Crime Rate,Residential Proportion,non-retail business acres/Town,Charles River,NO2 concentration,Average Rooms/Dwelling.,Prior Built Units Proportion,Distance to Employment Centres,Radial Highways Distance,ValueProperty/tax rate,Teacher/town,blacks/town,Lower Status Percent,median home price
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [7]:
df.isnull().sum()

Crime Rate                        0
Residential Proportion            0
non-retail business acres/Town    0
Charles River                     0
NO2 concentration                 0
Average Rooms/Dwelling.           0
Prior Built Units Proportion      0
Distance to Employment Centres    0
Radial Highways Distance          0
ValueProperty/tax rate            0
Teacher/town                      0
blacks/town                       0
Lower Status Percent              0
median home price                 0
dtype: int64

###  Preprocessing of categorical variables

In [8]:
df_OneHot = pd.get_dummies(df, columns=['Residential Proportion','Charles River'])

In [9]:
df=df_OneHot.copy()

In [10]:
df.head()

,Crime Rate,non-retail business acres/Town,NO2 concentration,Average Rooms/Dwelling.,Prior Built Units Proportion,Distance to Employment Centres,Radial Highways Distance,ValueProperty/tax rate,Teacher/town,blacks/town,...,Residential Proportion_70.0,Residential Proportion_75.0,Residential Proportion_80.0,Residential Proportion_82.5,Residential Proportion_85.0,Residential Proportion_90.0,Residential Proportion_95.0,Residential Proportion_100.0,Charles River_0.0,Charles River_1.0
0,0.00632,2.31,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,...,0,0,0,0,0,0,0,0,1,0
1,0.02731,7.07,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,...,0,0,0,0,0,0,0,0,1,0
2,0.02729,7.07,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,...,0,0,0,0,0,0,0,0,1,0
3,0.03237,2.18,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,...,0,0,0,0,0,0,0,0,1,0
4,0.06905,2.18,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,...,0,0,0,0,0,0,0,0,1,0

## Creating independent and dependent variables

In [11]:
X = df.drop(['median home price'], axis=1)
Y = df[['median home price']]
print(X.shape)
print(Y.shape)

(506, 39)
(506, 1)

## Normalization

In [12]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
x_scaled_minmax = min_max_scaler.fit_transform(X)
X = pd.DataFrame(x_scaled_minmax, columns = X.columns)
X.head()

,Crime Rate,non-retail business acres/Town,NO2 concentration,Average Rooms/Dwelling.,Prior Built Units Proportion,Distance to Employment Centres,Radial Highways Distance,ValueProperty/tax rate,Teacher/town,blacks/town,...,Residential Proportion_70.0,Residential Proportion_75.0,Residential Proportion_80.0,Residential Proportion_82.5,Residential Proportion_85.0,Residential Proportion_90.0,Residential Proportion_95.0,Residential Proportion_100.0,Charles River_0.0,Charles River_1.0
0,0.000000,0.067815,0.314815,0.577505,0.641607,0.269203,0.000000,0.208015,0.287234,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.000236,0.242302,0.172840,0.547998,0.782698,0.348962,0.043478,0.104962,0.553191,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.000236,0.242302,0.172840,0.694386,0.599382,0.348962,0.043478,0.104962,0.553191,0.989737,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.000293,0.063050,0.150206,0.658555,0.441813,0.448545,0.086957,0.066794,0.648936,0.994276,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.000705,0.063050,0.150206,0.687105,0.528321,0.448545,0.086957,0.066794,0.648936,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

## Train test data split

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtrain,xtest,ytrain,ytest =   train_test_split(X, Y, test_size=0.30, random_state=25,shuffle=True)
print(xtrain.shape, ytrain.shape)
print(xtest.shape, ytest.shape)

(354, 39) (354, 1)
(152, 39) (152, 1)

## Linear regression

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lr = LinearRegression()

In [17]:
lr.fit(xtrain,ytrain)

LinearRegression()

## Prediction using traing dataset

In [19]:
lr_predict_train = lr.predict(xtrain)
lr_predict_train[:5]

array([[35.515625  ],
       [18.33984375],
       [11.53515625],
       [20.28515625],
       [33.140625  ]])

## Prediction using test dataset

In [21]:
lr_predict = lr.predict(xtest)
lr_predict[:5]

array([[23.625     ],
       [19.4296875 ],
       [25.05859375],
       [ 6.76953125],
       [17.98046875]])

## RMSE and R2 score

In [22]:
from sklearn.metrics import r2_score

In [23]:
from sklearn.metrics import mean_squared_error

In [24]:
# model evaluation for training set
y_train_predict = lr.predict(xtrain)
rmse = (np.sqrt(mean_squared_error(ytrain, y_train_predict)))
r2 = r2_score(ytrain, y_train_predict)

print("The model performance for training set")
print("--------------------------------------")
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))
print("\n")

# model evaluation for testing set
y_test_predict = lr.predict(xtest)
rmse = (np.sqrt(mean_squared_error(ytest, y_test_predict)))
r2 = r2_score(ytest, y_test_predict)

print("The model performance for testing set")
print("--------------------------------------")
print('RMSE is {}'.format(rmse))
print('R2 score is {}'.format(r2))

The model performance for training set
--------------------------------------
RMSE is 4.489573015582216
R2 score is 0.7717449625929772


The model performance for testing set
--------------------------------------
RMSE is 4.713686756849728
R2 score is 0.7051089352341646